apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yu7p09wl3-nodejs-gitops
  description: This is GitOps manifest for yu7p09wl3-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: yu7p09wl3-nodejs
    janus-idp.io/tekton: yu7p09wl3-nodejs 
    backstage.io/kubernetes-id: yu7p09wl3-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yu7p09wl3-nodejs
