apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yu7p09wl3-nodejs
  janus-idp.io/tekton: yu7p09wl3-nodejs
  backstage.io/kubernetes-id: yu7p09wl3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yu7p09wl3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
